In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import recall_score, precision_score, f1_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [2]:
sonar = pd.read_csv(r"/home/sarthakredasani/Documents/CDAC_ML/Cases/Cases/Sonar/Sonar.csv")
sonar.head(5)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [ ]:
X, y = sonar.drop('Class', axis=1), sonar['Class']
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25, stratify=y)

In [4]:
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.7936507936507936

In [5]:
Cs = np.linspace(0.01, 5, 20)
scores = []
for c in Cs:
    svm = SVC(kernel='linear',C=c)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    scores.append([c,(accuracy_score(y_test, y_pred))])

In [6]:
df_scores = pd.DataFrame(scores, columns=['C', 'score'])
df_scores.sort_values('score', ascending=False)

           C     score
10  2.636316  0.809524
11  2.898947  0.809524
18  4.737368  0.809524
17  4.474737  0.809524
16  4.212105  0.809524
15  3.949474  0.809524
14  3.686842  0.809524
13  3.424211  0.809524
12  3.161579  0.809524
19  5.000000  0.809524
9   2.373684  0.809524
8   2.111053  0.793651
7   1.848421  0.793651
6   1.585789  0.793651
5   1.323158  0.793651
4   1.060526  0.793651
3   0.797895  0.777778
1   0.272632  0.761905
2   0.535263  0.761905
0   0.010000  0.539683

In [7]:
# Radial Kernel

In [8]:
svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.7619047619047619

In [9]:
Cs = np.linspace(0.01, 5, 20)
Gs = np.linspace(0.01, 5, 20)
scores = []
for c in Cs:
    for g in Gs:
        svm = SVC(kernel='rbf', C=c, gamma=g)
        svm.fit(X_train, y_train)
        y_pred = svm.predict(X_test)
        scores.append([c,g,(accuracy_score(y_test, y_pred))])

In [10]:
df_scores = pd.DataFrame(scores, columns=['C','Gamma', 'score'])
df_scores.sort_values('score', ascending=False)

            C     Gamma     score
105  1.323158  1.323158  0.888889
126  1.585789  1.585789  0.888889
347  4.474737  1.848421  0.873016
169  2.111053  2.373684  0.873016
149  1.848421  2.373684  0.873016
..        ...       ...       ...
32   0.272632  3.161579  0.539683
33   0.272632  3.424211  0.539683
34   0.272632  3.686842  0.539683
35   0.272632  3.949474  0.539683
0    0.010000  0.010000  0.539683

[400 rows x 3 columns]